/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abrashai' at '3/28/17 1:11 PM' with Gradle 2.13
 *
 * @author abrashai, @date 3/28/17 1:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
